#!/usr/bin/env bash
# Regenerate syntax/stryke.vim from the stryke binary's own reflection tables.
# Run after a stryke upgrade so the highlighter never drifts from the language.
#
#   ./scripts/gen_syntax.sh        # uses `stryke` on $PATH
#   STRYKE=/path/to/stryke ./scripts/gen_syntax.sh
#
# Sources of truth (the binary, not a hand-maintained list):
#   keywords : stryke -E 'p join "\n", sort keys %k'
#   builtins : stryke -E 'p join "\n", sort keys %b'
#   parallel : stryke -E 'p join "\n", sort @{$c{parallel}}'
set -euo pipefail

stryke="${STRYKE:-stryke}"
here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/syntax/stryke.vim"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

"$stryke" 'p join "\n", sort keys %b'            > "$tmp/builtins.txt"
"$stryke" 'p join "\n", sort @{$c{parallel}}'    | sort -u > "$tmp/parallel.txt"
ver="$("$stryke" --version 2>/dev/null | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
nb="$(wc -l < "$tmp/builtins.txt" | tr -d ' ')"

# Partition: parallel builtins, then everything else minus the constants that
# get their own highlight group.
sort -u "$tmp/builtins.txt" > "$tmp/b_sorted.txt"
comm -12 "$tmp/parallel.txt" "$tmp/b_sorted.txt" > "$tmp/par_in_b.txt"
printf 'true\nfalse\nundef\nnull\n' | sort -u > "$tmp/consts.txt"
comm -23 "$tmp/b_sorted.txt" "$tmp/par_in_b.txt" | comm -23 - "$tmp/consts.txt" > "$tmp/plain.txt"

# `:syntax keyword` rejects names that collide with its own argument keywords
# (E395), e.g. a builtin literally named `contains` or `fold`. Pull those out
# and emit them with `:syntax match \<word\>` instead.
printf '%s\n' contained containedin nextgroup transparent skipwhite skipnl \
  skipempty contains oneline fold display extend conceal cchar concealends \
  keepend excludenl | sort -u > "$tmp/reserved.txt"
comm -12 "$tmp/reserved.txt" "$tmp/plain.txt"     > "$tmp/resv_plain.txt"
comm -12 "$tmp/reserved.txt" "$tmp/par_in_b.txt"  > "$tmp/resv_par.txt"
comm -23 "$tmp/plain.txt"    "$tmp/reserved.txt"   > "$tmp/plain_safe.txt"
comm -23 "$tmp/par_in_b.txt" "$tmp/reserved.txt"   > "$tmp/par_safe.txt"

wrap() { awk -v g="$1" 'BEGIN{n=0}
  {if(n==0)printf "syntax keyword %s",g; printf " %s",$0; n++; if(n==15){print "";n=0}}
  END{if(n>0)print ""}'; }
matchwords() { awk -v g="$1" '{printf "syntax match %s \"\\<%s\\>\"\n",g,$0}'; }

{
cat <<HEAD
" vim-stryke — syntax highlighting for the stryke language
"
" GENERATED by scripts/gen_syntax.sh from the stryke binary's reflection tables
" (%k keywords, %b builtins, \$c{parallel}). A standalone stryke grammar — NOT a
" reskin of Vim's perl syntax. Regenerate after a stryke upgrade; do not edit by
" hand.
"
" Generated against stryke ${ver:-unknown} — ${nb} builtins.

if exists('b:current_syntax')
  finish
endif

syntax case match
syntax sync minlines=50

" ---------------------------------------------------------------------------
" Comments / POD / shebang
" ---------------------------------------------------------------------------
syntax keyword strykeTodo contained TODO FIXME XXX NOTE HACK
syntax match   strykeComment "#.*\$" contains=strykeTodo,@Spell
syntax match   strykeShebang "\%^#!.*\$"
syntax region  strykePod start="^=\a" end="^=cut\>" end="\%\$" contains=strykeTodo,@Spell

" ---------------------------------------------------------------------------
" Numbers
" ---------------------------------------------------------------------------
syntax match strykeNumber "\<\d\+\%(_\d\+\)*\>"
syntax match strykeNumber "\<0x\x\+\>"
syntax match strykeNumber "\<0b[01]\+\>"
syntax match strykeNumber "\<0o\?\o\+\>"
syntax match strykeFloat  "\<\d\+\%(_\d\+\)*\.\d\+\%([eE][-+]\?\d\+\)\?\>"
syntax match strykeFloat  "\<\d\+[eE][-+]\?\d\+\>"

" ---------------------------------------------------------------------------
" Variables (sigils)
" ---------------------------------------------------------------------------
syntax match strykeTopicVar  "\$_\>"
syntax match strykeSpecialVar "\$[!@/\\&\`'+0-9.,;^]"
syntax match strykeSpecialVar "@_\>"
syntax match strykeSpecialVar "\$#\h\w*"
syntax match strykeScalar "\$\$\?\h\w*\%(::\h\w*\)*"
syntax match strykeArray  "@\$\?\h\w*\%(::\h\w*\)*"
syntax match strykeHash   "%\$\?\h\w*\%(::\h\w*\)*"

" ---------------------------------------------------------------------------
" Strings
" ---------------------------------------------------------------------------
syntax match  strykeStringEscape contained "\\\\."
syntax match  strykeInterp contained "\$\h\w*\%(::\h\w*\)*"
syntax match  strykeInterp contained "@\h\w*"
syntax region strykeInterp contained matchgroup=strykeInterp start="\${" end="}" contains=TOP

syntax region strykeStringS  start=+'+ skip=+\\\\'+ end=+'+ contains=strykeStringEscape
syntax region strykeStringD  start=+"+ skip=+\\\\"+ end=+"+ contains=strykeStringEscape,strykeInterp,@Spell
syntax region strykeBacktick start=+\`+ skip=+\\\\\`+ end=+\`+ contains=strykeStringEscape,strykeInterp

syntax region strykeQw start=+\<qw\s*(+ end=+)+ contains=NONE
syntax region strykeQw start=+\<qw\s*{+ end=+}+ contains=NONE
syntax region strykeQw start=+\<qw\s*\[+ end=+\]+ contains=NONE
syntax region strykeQw start=+\<qw\s*/+ end=+/+ contains=NONE
syntax region strykeStringD start=+\<\%(qq\|qx\)\s*(+ end=+)+ contains=strykeStringEscape,strykeInterp
syntax region strykeStringD start=+\<\%(qq\|qx\)\s*{+ end=+}+ contains=strykeStringEscape,strykeInterp
syntax region strykeStringS start=+\<q\s*(+ end=+)+ contains=strykeStringEscape
syntax region strykeStringS start=+\<q\s*{+ end=+}+ contains=strykeStringEscape

syntax region strykeHereDoc matchgroup=strykeStringD start=+<<\~\?"\=\z(\h\w*\)"\=+ end=+^\s*\z1\$+ contains=strykeInterp,strykeStringEscape
syntax region strykeHereDoc matchgroup=strykeStringS start=+<<\~\?'\z(\h\w*\)'+ end=+^\s*\z1\$+

" ---------------------------------------------------------------------------
" Regex
" ---------------------------------------------------------------------------
syntax match  strykeRegexBind "=\~\|!\~"
syntax region strykeRegex matchgroup=strykeRegexDelim start=+\<m\s*/+ skip=+\\\\/+ end=+/[a-z]*+
syntax region strykeRegex matchgroup=strykeRegexDelim start=+\<qr\s*/+ skip=+\\\\/+ end=+/[a-z]*+
syntax region strykeRegex matchgroup=strykeRegexDelim start=+\<s\s*/+ skip=+\\\\/+ end=+/[a-z]*+
syntax region strykeRegex matchgroup=strykeRegexDelim start=+\<\%(tr\|y\)\s*/+ skip=+\\\\/+ end=+/[a-z]*+

" ---------------------------------------------------------------------------
" Keywords (the %k table, categorized)
" ---------------------------------------------------------------------------
syntax keyword strykeDecl my var val mysync varsync our oursync local state const frozen typed use no import package require pub priv
syntax keyword strykeFnKeyword fn sub class enum struct trait impl extends after around before
syntax keyword strykeControl return if elsif else unless until while for foreach do last next redo loop continue goto given when default match try catch finally defer eval
syntax keyword strykeConcurrent async await spawn
syntax keyword strykeWordOp and or not xor cmp eq ne lt le gt ge x
syntax keyword strykeBoolean true false
syntax keyword strykeUndef undef null
syntax match   strykeMagic "\<__\%(FILE\|LINE\|PACKAGE\|SUB\|DATA\|END\)__\>"
syntax keyword strykePhase BEGIN END INIT CHECK UNITCHECK

" ---------------------------------------------------------------------------
" Builtins (the complete %b table) — parallel subset first
" ---------------------------------------------------------------------------
HEAD

wrap strykeBuiltinPar < "$tmp/par_safe.txt"
wrap strykeBuiltin    < "$tmp/plain_safe.txt"
# reserved-word builtins (collide with :syntax keyword args) via :syntax match
matchwords strykeBuiltinPar < "$tmp/resv_par.txt"
matchwords strykeBuiltin    < "$tmp/resv_plain.txt"

cat <<'TAIL'

" ---------------------------------------------------------------------------
" Optional type names (typed my $x : Int|Str|Float ; fn ($a: Int) {})
" ---------------------------------------------------------------------------
syntax keyword strykeType Int Str Float Bool Num Any Array Hash List Map Set Void

" ---------------------------------------------------------------------------
" Operators (thread macros, arrows, ranges)
" ---------------------------------------------------------------------------
syntax match strykeThreadArrow "\~p\?d\?s\?>>\?\|->>"
syntax match strykeOperator    "|>\|=>\|->\|\.\.\.\?\|::"
syntax match strykeOperator    "[-+*/%.]=\?\|\*\*\|==\|!=\|<=>\|<=\|>=\|<\|>\|&&\|||\|//\|!\|?\|\\"

" ---------------------------------------------------------------------------
" Highlight links
" ---------------------------------------------------------------------------
highlight default link strykeComment      Comment
highlight default link strykeShebang      PreProc
highlight default link strykePod          Comment
highlight default link strykeTodo         Todo
highlight default link strykeNumber       Number
highlight default link strykeFloat        Float
highlight default link strykeTopicVar     Special
highlight default link strykeSpecialVar   Special
highlight default link strykeScalar       Identifier
highlight default link strykeArray        Identifier
highlight default link strykeHash         Identifier
highlight default link strykeStringS      String
highlight default link strykeStringD      String
highlight default link strykeBacktick     String
highlight default link strykeQw           String
highlight default link strykeHereDoc      String
highlight default link strykeStringEscape SpecialChar
highlight default link strykeInterp       Identifier
highlight default link strykeRegex        String
highlight default link strykeRegexDelim   Delimiter
highlight default link strykeRegexBind    Operator
highlight default link strykeDecl         StorageClass
highlight default link strykeFnKeyword    Keyword
highlight default link strykeControl      Statement
highlight default link strykeConcurrent   Keyword
highlight default link strykePhase        PreProc
highlight default link strykeBoolean      Boolean
highlight default link strykeUndef        Constant
highlight default link strykeWordOp       Operator
highlight default link strykeMagic        Constant
highlight default link strykeBuiltin      Function
highlight default link strykeBuiltinPar   Function
highlight default link strykeType         Type
highlight default link strykeThreadArrow  Operator
highlight default link strykeOperator     Operator

let b:current_syntax = 'stryke'
TAIL
} > "$out"

echo "wrote $out ($(wc -l < "$out" | tr -d ' ') lines, $nb builtins, stryke ${ver:-unknown})"
